### ISSUE TITLE
Capture datetime object in mysql database

### ISSUE THREAD

**Issue by echibuogwu** [siddhi-io/siddhi-io-cdc#37]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by echibuogwu** [comment]
please am having difficulty capturing a datatime field in a stream definition using cdc extension to connect to a mysql database..
**My stream definition is:**
`define stream TestStream(id int, transmissiondate string);`

**Error**: _Value 2019-10-18 19:58:37.0 is not compatible with type STRING,Hence dropping the message_

Kindly assist

**Comment by mohanvive** [comment]
Fixed in https://github.com/siddhi-io/siddhi-map-keyvalue/pull/37 and https://github.com/siddhi-io/siddhi-map-keyvalue/pull/35
