### ISSUE TITLE
CDC with PostgreSQL only supports decoderbufs logical decoding output plug-in

### ISSUE THREAD

**Issue by AnuGayan** [siddhi-io/siddhi-io-cdc#64]
**Description:**
Current siddhi-io-cdc 2.0.8 does not support logical decoding output plug-in except **decoderbufs** since "plugin.name" is not configurable in current implementation.

**Affected Product Version:**
All the versions upto siddhi-io-cdc 2.0.8

**Comment by kiwinesian** [comment]
ditto this. 🙏

**Comment by senthuran16** [comment]
Closing this, since this has been addressed via https://github.com/siddhi-io/siddhi-io-cdc/pull/72
