### ISSUE TITLE
Allow slot replication selection for PostgreSQL database

### ISSUE THREAD

**Issue by kiwinesian** [siddhi-io/siddhi-io-cdc#70]
**Description:**
PostgreSQL requires a unique replication slot for each method: `CREATE`, `UPDATE`, `DELETE`
The siddhi-io-cdc doesn't have the option to change `slot.name` and create respective replication slot for each method.

`slot.name` is default to `Debezium` at the moment.

**Suggested Labels:**
psql, postgresql, replication

**Suggested Assignees:**

**Affected Product Version:**
2.0.9 and earlier

**OS, DB, other environment details and versions:**    
Debian 10.x

**Steps to reproduce:**
Regular psql connection

**Related Issues:**

**Comment by senthuran16** [comment]
Closing this, since this has been addressed via https://github.com/siddhi-io/siddhi-io-cdc/pull/72
